### ISSUE TITLE
Getting error after running project.

### ISSUE THREAD

**Issue by Redowanur** [sowmen/FXSimulator_1.0#3]
@sowmen 
I have tried running your project in netbeans. But I am getting some errors. I am giving the screenshot below.

![Screenshot (208)](https://user-images.githubusercontent.com/69495647/176670980-e0a30b59-a4ac-40c3-b34c-00e75e7207ff.png)

Could you please tell me what is the problem here.

**Comment by sowmen** [comment]
The error says "Java executable not found in JDK". Your JDK installation is not correct. Try reinstalling JDK1.8 and check if your path variables are correct.

**Comment by Redowanur** [comment]
Still getting these errors.
![Screenshot (209)](https://user-images.githubusercontent.com/69495647/176681731-e344c538-ee36-4132-98a3-3e02ffc9e213.png)

**Comment by sowmen** [comment]
Did you try doing a clean rebuild?
